### ISSUE TITLE
Plugin broken with Tox >= 3.8.0

### ISSUE THREAD

**Issue by wcooley** [useblocks/tox-envreport#3]
The plugin is broken with Tox >= 3.8.0:
```
Traceback (most recent call last):
  ...
  File ".../venvs/tox/lib/python3.6/site-packages/pluggy/hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File ".../venvs/tox/lib/python3.6/site-packages/pluggy/manager.py", line 68, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File ".../venvs/tox/lib/python3.6/site-packages/pluggy/manager.py", line 62, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File ".../venvs/tox/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File ".../venvs/tox/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File ".../venvs/tox/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File ".../venvs/tox/lib/python3.6/site-packages/tox_envreport/plugin.py", line 26, in tox_runtest_post
    tox_workdir = venv.session.config.toxworkdir.strpath
AttributeError: 'VirtualEnv' object has no attribute 'session'
```

This is the same problem reported by several other projects:
* tox-dev/tox-pipenv#61
* tox-dev/tox-conda#15
* encode/django-rest-framework#6546

**Comment by danwos** [comment]
Thanks for reporting this problem.
I will release the fix as version 0.2.1 shortly.
